version: '3.8'

services:
  web: 
    build: .
    env_file:
      - .env
    ports: 
      - 3000:3000
    volumes:
      - .:/app
    command: air cmd/main.go -b 0.0.0.0 -buildvcs=false
  db: 
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
